name: AA-Project
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - scipy
  - requests_cache
  - ipykernel
  - pip:
      - openmeteo_requests
      - retry_requests
